import { beforeEach, describe, expect, it, vi } from 'vitest';

const mocks = vi.hoisted(() => ({
  upload: vi.fn(),
  getPublicUrl: vi.fn(),
}));

vi.mock('@/lib/secret-registry', () => ({
  getSecret: (key: string) => key === 'GEMINI_API_KEY' ? 'test-gemini-key' : null,
}));

vi.mock('@/lib/supabase', () => ({
  supabaseAdmin: {
    storage: {
      from: () => ({
        upload: mocks.upload,
        getPublicUrl: mocks.getPublicUrl,
      }),
    },
  },
}));
import {
  buildGeneratedBlogImagePrompt,
  buildSearchQuery,
  extractGeminiInteractionImage,
  generateSectionImage,
  isGeneratedBlogImageUrl,
} from './blog-image-gen';

describe('blog image generation contract', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    mocks.upload.mockReset().mockResolvedValue({ error: null });
    mocks.getPublicUrl.mockReset().mockReturnValue({
      data: {
        publicUrl: 'https://project.supabase.co/storage/v1/object/public/blog-assets/generated/blog/ab/hash.jpg',
      },
    });
  });

  it('uses the destination mapping for Korean destination search queries', () => {
    expect(buildSearchQuery('월별 날씨와 옷차림', '광저우', '광저우 월별 날씨'))
      .toContain('Guangzhou China Canton Tower');
  });

  it('extracts an image from the current Interactions API response shape', () => {
    expect(extractGeminiInteractionImage({
      steps: [{
        type: 'model_output',
        content: [{ type: 'image', data: 'base64-image', mime_type: 'image/jpeg' }],
      }],
    })).toEqual({ data: 'base64-image', mimeType: 'image/jpeg' });
  });

  it('keeps generated prompts free of text overlays and documentary claims', () => {
    const prompt = buildGeneratedBlogImagePrompt('Guangzhou seasonal travel scene');
    expect(prompt).toContain('No text');
    expect(prompt).toContain('not documentary proof');
  });

  it('recognizes only persisted public generated-image URLs', () => {
    expect(isGeneratedBlogImageUrl(
      'https://project.supabase.co/storage/v1/object/public/blog-assets/generated/blog/ab/hash.jpg',
    )).toBe(true);
    expect(isGeneratedBlogImageUrl('data:image/jpeg;base64,abc')).toBe(false);
  });

  it('persists generated bytes and returns a public URL instead of a data URL', async () => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response(JSON.stringify({
      steps: [{
        type: 'model_output',
        content: [{
          type: 'image',
          data: Buffer.from('generated-image-bytes').toString('base64'),
          mime_type: 'image/jpeg',
        }],
      }],
    }), { status: 200 })));

    const url = await generateSectionImage('월별 날씨와 옷차림', '광저우 월별 날씨', '광저우');

    expect(url).toMatch(/^https:\/\//);
    expect(url).not.toContain('data:image');
    expect(mocks.upload).toHaveBeenCalledWith(
      expect.stringMatching(/^generated\/blog\/[a-f0-9]{2}\/[a-f0-9]{64}\.jpg$/),
      expect.any(Buffer),
      expect.objectContaining({ contentType: 'image/jpeg', upsert: false }),
    );
    expect(fetch).toHaveBeenCalledWith(
      'https://generativelanguage.googleapis.com/v1beta/interactions',
      expect.objectContaining({ method: 'POST' }),
    );
  });
});
