export const BLOG_SLUG_REDIRECTS: Record<string, string> = {
  '7-bali': 'bali-july-weather-checklist',
  'post-hv01': 'travel-emergency-medicine-summer-checklist',
  '7-top-5': 'europe-july-cool-cities-top-5',
  '7-weather': 'sydney-july-winter-weather-guide',
  'visa-2026': 'vietnam-visa-entry-documents-2026',
  '6-nagasaki': 'nagasaki-travel-cost-preparation-tips-2026',
  'hohhot-6': 'hohhot-monthly-weather-clothes-2026',
  'nagasaki-34': 'nagasaki-budget-cost-guide-2026',
  'danang-best': 'danang-budget-cost-guide-2026',
  'danang-34': 'danang-itinerary-route-guide-2026',
  'bohol-34': 'bohol-budget-cost-guide-2026',
  'nagasaki-6': 'nagasaki-monthly-weather-clothes-2026',
  'post-yd8p': 'summer-travel-insurance-coverage-guide-2026',
  'vs-vs-esim-7': 'overseas-roaming-usim-esim-comparison-2026',
  '7-guide-f4aa5972': 'europe-independent-travel-tips-july-2026',
  'post-uo8h': 'summer-airport-crowding-departure-tips-2026',
  '7-post-s3gj': 'july-overseas-flight-ticket-booking-tips-2026',
  'mongolia-preparation-qcb0421c1': 'mongolia-july-weather-clothes-checklist-2026',
  'travel-guide-q35bf6ed0': 'july-family-travel-weather-clothes-checklist-2026',
  'singapore-guide-qdfda9604': 'singapore-july-weather-clothes-checklist-2026',
  'travel-guide-e4c4d970': 'osaka-july-weather-clothes-checklist-2026',
  '7-cebu-preparation': 'cebu-july-weather-clothes-checklist-2026',
  'travel-preparation-f892b636': 'clark-travel-preparation-budget-checklist-2026',
  '7-guam-preparation': 'guam-travel-budget-cost-checklist-2026',
  '7-danang-weather': 'danang-july-rainy-season-weather-tips-2026',
  '7-bangkok-weather-complete-guide': 'bangkok-weather-clothes-checklist-2026',
  '7-mongolia-preparation': 'mongolia-july-peak-season-preparation-checklist-2026',
  '5-post-1k2q': 'overseas-travel-preparation-budget-checklist-2026',
  '3-post-yb6e': 'travel-preparation-budget-cost-checklist-2026',
  '6-vs-danang-boracay-kotakinabalu': 'southeast-asia-danang-boracay-kotakinabalu-comparison-2026',
  '6-okinawa': 'okinawa-travel-cost-preparation-tips-2026',
  '6-fukuoka': 'fukuoka-june-weather-rainy-day-itinerary-2026',
  '6-bangkok': 'bangkok-june-rainy-season-weather-preparation-2026',
  '6-danang': 'danang-weather-clothes-checklist-2026',
  '일본-포켓와이파이-vs-유심-vs-esim-나에게-맞는-선택은-재작성-v2': 'japan-pocket-wifi-usim-esim-comparison-2026',
  '6월-유럽-여행-성수기-전-항공권-저렴하게-예약하는-팁-재작성-v2': 'europe-june-flight-booking-tips-2026',
  '여름방학-유럽-배낭여행-3주-경비-현실적으로-계산하기-재작성-v2': 'europe-summer-backpacking-3week-budget-2026',
  '5월-황금연휴-해외여행-비행시간-짧은-동남아-휴양지-추천-재작성-v2': 'southeast-asia-short-flight-holiday-destinations-2026',
  '태국-입국-시-필요한-서류와-면세-한도-총정리-2026년-기준-재작성-v2': 'thailand-entry-documents-duty-free-2026',
};

export function resolveBlogSlugRedirect(slug: string): string | null {
  return BLOG_SLUG_REDIRECTS[slug] ?? null;
}
