/**
 * Secret Registry
 * - 비즈니스 로직에서 process.env 직접 접근 대신 이 레이어를 사용한다.
 * - 신규 키 추가 시 여기에만 정의하면 감사/검증 지점이 단일화된다.
 *
 * ⚠️ 클라이언트 컴포넌트(`'use client'`)에서는 사용 금지.
 * `getSecret()` 의 `process.env[key]` 동적 인덱싱은 webpack 이 inline 못해서
 * client bundle 에서 항상 `null` 반환. NEXT_PUBLIC_* 가 필요한 client 코드는
 * 반드시 `process.env.NEXT_PUBLIC_X` 정적 참조를 직접 사용하라.
 *
 * 사례: ERR-secret-registry-client-bundle@2026-05-10
 *   /m/admin/* + /auth/callback + usePushSubscription 등이 이 패턴으로 크래시함.
 */

export type SecretKey =
  | 'CRON_SECRET'
  | 'AD_OS_SAFE_PIPELINE_CRON_PIPELINES'
  | 'AD_OS_CONVERSION_UPLOAD_ENABLED'
  | 'AD_OS_GOOGLE_CONVERSION_UPLOAD_ENABLED'
  | 'AD_OS_META_CAPI_UPLOAD_ENABLED'
  | 'AD_OS_NAVER_LIMITED_WRITE_ENABLED'
  | 'ADMIN_API_TOKEN'
  | 'NEXT_PUBLIC_SUPABASE_ANON_KEY'
  | 'SUPABASE_ANON_KEY'
  | 'SUPABASE_PUBLISHABLE_KEY'
  | 'SUPABASE_SECRET_KEY'
  | 'SUPABASE_SECRET_DEFAULT_KEY'
  | 'SUPABASE_SERVICE_KEY'
  | 'SUPABASE_SERVICE_ROLE_KEY'
  | 'SUPABASE_JWT_SECRET'
  | 'DESIGN_PREVIEW_SECRET'
  | 'DEEPSEEK_API_KEY'
  | 'ANTHROPIC_API_KEY'
  | 'GEMINI_API_KEY'
  | 'GOOGLE_AI_API_KEY'
  | 'PEXELS_API_KEY'
  | 'SOLAPI_API_KEY'
  | 'SOLAPI_API_SECRET'
  | 'KAKAO_CHANNEL_ID'
  | 'KAKAO_SENDER_NUMBER'
  | 'KAKAO_TEMPLATE_REVIEW_REQUEST'
  | 'KAKAO_TEMPLATE_MAGIC_LINK'
  | 'META_ACCESS_TOKEN'
  | 'META_CAPI_ACCESS_TOKEN'
  | 'META_GRAPH_API_VERSION'
  | 'NEXT_PUBLIC_META_PIXEL_ID'
  | 'META_PIXEL_ID'
  | 'META_IG_USER_ID'
  | 'META_AD_ACCOUNT_ID'
  | 'META_PAGE_ID'
  | 'META_APP_ID'
  | 'META_APP_SECRET'
  | 'META_WEBHOOK_VERIFY_TOKEN'
  | 'META_GRAPH_ACCESS_TOKEN'
  | 'META_ADS_ACCESS_TOKEN'
  | 'THREADS_APP_ID'
  | 'THREADS_APP_SECRET'
  | 'THREADS_ACCESS_TOKEN'
  | 'THREADS_USER_ID'
  | 'OAUTH_STATE_SECRET'
  | 'NAVER_CLIENT_ID'
  | 'NAVER_CLIENT_SECRET'
  | 'NAVER_BLOG_ACCESS_TOKEN'
  | 'RESEND_API_KEY'
  | 'VA_EMAILS'
  | 'SERPAPI_KEY'
  | 'GSC_SERVICE_ACCOUNT'
  | 'GSC_SITE_URL'
  | 'TOSS_SECRET_KEY'
  | 'LTR_TRAINING_SECRET'
  | 'SLACK_SIGNING_SECRET'
  | 'SLACK_BOT_TOKEN'
  | 'SLACK_CHANNEL_ID'
  | 'SLACK_ALERT_WEBHOOK_URL'
  | 'SLACK_ALERTS_WEBHOOK'
  | 'SLACK_GROUP_RFQ_WEBHOOK_URL'
  | 'SLACK_PAYMENTS_WEBHOOK_URL'
  | 'SLACK_WEBHOOK_URL'
  | 'SMS_WEBHOOK_SECRET'
  | 'KAKAO_CHANNEL_SECRET'
  | 'GOOGLE_ADS_CLIENT_ID'
  | 'GOOGLE_ADS_CLIENT_SECRET'
  | 'GOOGLE_ADS_DEVELOPER_TOKEN'
  | 'GOOGLE_ADS_CUSTOMER_ID'
  | 'GOOGLE_ADS_ACCESS_TOKEN'
  | 'GOOGLE_ADS_REFRESH_TOKEN'
  | 'GOOGLE_ADS_CONVERSION_ACTION_ID'
  | 'GOOGLE_ADS_API_VERSION'
  | 'NAVER_ADS_API_KEY'
  | 'NAVER_ADS_SECRET_KEY'
  | 'NAVER_ADS_CUSTOMER_ID'
  | 'VAPID_PRIVATE_KEY'
  | 'NEXT_PUBLIC_VAPID_PUBLIC_KEY'
  | 'REVALIDATE_SECRET'
  | 'GUEST_PORTAL_SESSION_SECRET'
  | 'MYREALTRIP_API_KEY'
  | 'GOOGLE_API_KEY'
  | 'GOOGLE_GEMINI_API_KEY'
  | 'GOOGLE_PAGESPEED_API_KEY'
  | 'GSC_SERVICE_ACCOUNT_JSON'
  | 'GOOGLE_SERVICE_ACCOUNT_JSON'
  | 'GSC_SITE_URL'
  | 'IR_CANARY_ENABLED'
  | 'IR_CANARY_ROLLOUT_PCT'
  | 'IR_CANARY_DEFAULT_ENGINE'
  | 'EXCHANGE_RATE_API_KEY'
  | 'GUIDEBOOK_TOKEN_SECRET'
  | 'MAGIC_LINK_SECRET'
  | 'MAGIC_SESSION_SECRET'
  | 'INDEXNOW_KEY'
  | 'GOOGLE_INDEXING_API_FOR_BLOGS'
  | 'AMADEUS_CLIENT_ID'
  | 'AMADEUS_CLIENT_SECRET'
  | 'AGODA_AFFILIATE_API_KEY'
  | 'SKYSCANNER_API_KEY'
  | 'ENCRYPTION_SECRET_KEY'
  | 'NEXT_PUBLIC_APP_URL'
  | 'NEXT_PUBLIC_BASE_URL'
  | 'NEXT_PUBLIC_GA4_ID'
  | 'NEXT_PUBLIC_NAVER_ANALYTICS_ID'
  | 'NEXT_PUBLIC_KAKAO_PIXEL_ID'
  | 'NEXT_PUBLIC_CLARITY_PROJECT_ID'
  | 'NEXT_PUBLIC_CONSULT_PHONE'
  | 'NEXT_PUBLIC_NAVER_ADS_API_KEY'
  | 'NEXT_PUBLIC_NAVER_ADS_CUSTOMER_ID'
  | 'NEXT_PUBLIC_GOOGLE_ADS_CUSTOMER_ID'
  | 'NEXT_PUBLIC_SITE_URL'
  | 'NEXT_PUBLIC_DEFAULT_TENANT_ID'
  | 'INSTAGRAM_BUSINESS_ACCOUNT_ID'
  | 'X_BEARER_TOKEN'
  | 'TWITTER_BEARER_TOKEN'
  | 'NAVER_CAFE_ID'
  | 'META_ADS_DRY_RUN'
  | 'META_ADS_TEST_MODE'
  | 'META_TEST_EVENT_CODE'
  | 'AFFILIATE_IP_SALT'
  | 'AFFILIATE_TOKEN_SECRET'
  | 'AFFILIATE_JWT_SECRET'
  | 'AFFILIATE_INVITE_CODES'
  | 'BAND_RSS_URL'
  | 'COMPANY_ACCOUNT'
  | 'GOOGLE_CONVERSION_ID'
  | 'MYREALTRIP_MYLINK_ID'
  | 'NEXT_PUBLIC_SUPABASE_URL'
  | 'OPS_VERCEL_DASHBOARD_URL'
  | 'RESEND_FROM_EMAIL'
  | 'SUPABASE_URL'
  | 'VA_EMAIL_FROM'
  | 'VAPID_SUBJECT'
  | 'UPSTASH_REDIS_REST_URL'
  | 'UPSTASH_REDIS_REST_TOKEN'
  | 'AI_IMAGE_GEN_ENABLED';

export function getSecret(key: SecretKey): string | null {
  const value = process.env[key];
  if (!value) return null;
  const trimmed = value.trim();
  if (!trimmed || trimmed === '""' || trimmed === "''") return null;
  return trimmed;
}

export function hasSecrets(keys: SecretKey[]): boolean {
  return keys.every((k) => !!getSecret(k));
}

export function getAiProviderSecret(provider: 'deepseek' | 'claude' | 'gemini'): string | null {
  if (provider === 'deepseek') return getSecret('DEEPSEEK_API_KEY');
  if (provider === 'claude') return getSecret('ANTHROPIC_API_KEY');
  return getSecret('GEMINI_API_KEY') || getSecret('GOOGLE_AI_API_KEY');
}

/**
 * 복원력 있는 LLM 설정 확인 — 하나 이상의 LLM 공급자 키가 설정되어 있으면 true.
 * DeepSeek + Gemini 중 하나라도 있으면 통과.
 */
export function hasResilientLlmConfig(): boolean {
  return Boolean(
    getSecret('DEEPSEEK_API_KEY') ||
      getSecret('GEMINI_API_KEY') ||
      getSecret('GOOGLE_AI_API_KEY'),
  );
}
